### ISSUE TITLE
bugs 'n' crashes

### ISSUE THREAD

**Issue by Rico040** [Rico040/bulls-and-cows#1]
### never gonna give this up
- [x] after updating dependency teh font gone 🥺
- [x] 9th manual page crushing with following error
```
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\code\Bulls and Cows\main.py", line 764, in <module>
    menu();  # good practice to avoid unwanted code execution
  File "C:\Users\Admin\Documents\code\Bulls and Cows\main.py", line 602, in menu
    main()
  File "C:\Users\Admin\Documents\code\Bulls and Cows\main.py", line 323, in main
    about(can_view)
  File "C:\Users\Admin\Documents\code\Bulls and Cows\main.py", line 541, in about
    floor.enabled = True
ffi.error: struct PhysicsBodyData: wrong size for field 'enabled' (cdef says 4, but C compiler says 1). fix it or use "...;" as the last field in the cdef for struct PhysicsBodyData to make it flexible
```
- [ ] cleanup code, remove repetitive code
- [x] crash when `max_char_input = 0` trying count similarty

**Comment by Rico040** [comment]
> after updating depedency teh font gone 🥺

just runned backup which is actually local git repo and font appeared 🤯

> 9th manual page crushing with following error

idk what the heck is this and why it's happening. commented code section for while.
